// Generated by scripts/sync-tracks.mjs — do not edit by hand.
// Source of truth: tracks.json

export type Track = {
  id: string;
  title: string;
  album: string;
  duration: string;
  src: string;
  artworkSrc?: string;
  soundcloudUrl?: string;
  mood?: import('./moods').MoodName;
  cover: {
    from: string;
    to: string;
    accent: string;
  };
};

export const tracks: Track[] = [
  {
    id: "01",
    title: "Frozen by J.A.D",
    album: "J.A.D",
    duration: "0:00",
    src: "/audio/frozen.mp3",
    artworkSrc: "/covers/01.jpg",
    soundcloudUrl: "https://soundcloud.com/jadsynth/frozen",
    cover: {
      from: "#1f2a3a",
      to: "#05080f",
      accent: "#d4a574",
    },
  },
  {
    id: "02",
    title: "Only in Time by J.A.D",
    album: "J.A.D",
    duration: "0:00",
    src: "/audio/only-in-time.mp3",
    artworkSrc: "/covers/02.jpg",
    soundcloudUrl: "https://soundcloud.com/jadsynth/only-in-time",
    cover: {
      from: "#1f2a3a",
      to: "#05080f",
      accent: "#d4a574",
    },
  },
  {
    id: "03",
    title: "In An Instant by J.A.D",
    album: "J.A.D",
    duration: "0:00",
    src: "/audio/in-an-instant.mp3",
    artworkSrc: "/covers/03.jpg",
    soundcloudUrl: "https://soundcloud.com/jadsynth/in-an-instant",
    cover: {
      from: "#1f2a3a",
      to: "#05080f",
      accent: "#d4a574",
    },
  },
  {
    id: "04",
    title: "Revolve by J.A.D",
    album: "J.A.D",
    duration: "0:00",
    src: "/audio/revolve.mp3",
    artworkSrc: "/covers/04.jpg",
    soundcloudUrl: "https://soundcloud.com/jadsynth/revolve",
    cover: {
      from: "#1f2a3a",
      to: "#05080f",
      accent: "#d4a574",
    },
  },
  {
    id: "05",
    title: "The End by J.A.D",
    album: "J.A.D",
    duration: "0:00",
    src: "/audio/the-end.mp3",
    artworkSrc: "/covers/05.jpg",
    soundcloudUrl: "https://soundcloud.com/jadsynth/the-end",
    cover: {
      from: "#1f2a3a",
      to: "#05080f",
      accent: "#d4a574",
    },
  },
  {
    id: "06",
    title: "Past by J.A.D",
    album: "J.A.D",
    duration: "0:00",
    src: "/audio/past.mp3",
    artworkSrc: "/covers/06.jpg",
    soundcloudUrl: "https://soundcloud.com/jadsynth/past",
    cover: {
      from: "#1f2a3a",
      to: "#05080f",
      accent: "#d4a574",
    },
  },
  {
    id: "07",
    title: "Wandering Moog by J.A.D",
    album: "J.A.D",
    duration: "0:00",
    src: "/audio/wandering-moog.mp3",
    artworkSrc: "/covers/07.jpg",
    soundcloudUrl: "https://soundcloud.com/jadsynth/wandering-moog",
    cover: {
      from: "#1f2a3a",
      to: "#05080f",
      accent: "#d4a574",
    },
  },
  {
    id: "08",
    title: "Wave by J.A.D",
    album: "J.A.D",
    duration: "0:00",
    src: "/audio/waves.mp3",
    artworkSrc: "/covers/08.jpg",
    soundcloudUrl: "https://soundcloud.com/jadsynth/wave",
    cover: {
      from: "#1f2a3a",
      to: "#05080f",
      accent: "#d4a574",
    },
  },
  {
    id: "09",
    title: "Froggy by J.A.D",
    album: "J.A.D",
    duration: "0:00",
    src: "/audio/froggy.mp3",
    artworkSrc: "/covers/09.jpg",
    soundcloudUrl: "https://soundcloud.com/jadsynth/froggy",
    cover: {
      from: "#1f2a3a",
      to: "#05080f",
      accent: "#d4a574",
    },
  },
  {
    id: "10",
    title: "Yellow Intobloo by J.A.D",
    album: "J.A.D",
    duration: "0:00",
    src: "/audio/interbloo.mp3",
    artworkSrc: "/covers/10.jpg",
    soundcloudUrl: "https://soundcloud.com/jadsynth/yellow-interbloo",
    cover: {
      from: "#1f2a3a",
      to: "#05080f",
      accent: "#d4a574",
    },
  },
  {
    id: "11",
    title: "Nightrider by J.A.D",
    album: "J.A.D",
    duration: "0:00",
    src: "/audio/nightrider.mp3",
    artworkSrc: "/covers/11.jpg",
    soundcloudUrl: "https://soundcloud.com/jadsynth/nightrider-wip",
    cover: {
      from: "#1f2a3a",
      to: "#05080f",
      accent: "#d4a574",
    },
  },
  {
    id: "12",
    title: "Dimensional Drift by J.A.D",
    album: "J.A.D",
    duration: "0:00",
    src: "/audio/dimensional-drift.mp3",
    artworkSrc: "/covers/12.jpg",
    soundcloudUrl: "https://soundcloud.com/jadsynth/level-one",
    cover: {
      from: "#1f2a3a",
      to: "#05080f",
      accent: "#d4a574",
    },
  },
  {
    id: "13",
    title: "Streamline by J.A.D",
    album: "J.A.D",
    duration: "0:00",
    src: "/audio/streamline.mp3",
    artworkSrc: "/covers/13.jpg",
    soundcloudUrl: "https://soundcloud.com/jadsynth/streamline",
    cover: {
      from: "#1f2a3a",
      to: "#05080f",
      accent: "#d4a574",
    },
  },
  {
    id: "14",
    title: "Timeless by J.A.D",
    album: "J.A.D",
    duration: "0:00",
    src: "/audio/timeless.mp3",
    artworkSrc: "/covers/14.jpg",
    soundcloudUrl: "https://soundcloud.com/jadsynth/timeless",
    cover: {
      from: "#1f2a3a",
      to: "#05080f",
      accent: "#d4a574",
    },
  },
  {
    id: "15",
    title: "Rend by J.A.D",
    album: "J.A.D",
    duration: "0:00",
    src: "/audio/rend.mp3",
    artworkSrc: "/covers/15.jpg",
    soundcloudUrl: "https://soundcloud.com/jadsynth/rend",
    cover: {
      from: "#1f2a3a",
      to: "#05080f",
      accent: "#d4a574",
    },
  },
  {
    id: "16",
    title: "Sender by J.A.D",
    album: "J.A.D",
    duration: "0:00",
    src: "/audio/sender.mp3",
    artworkSrc: "/covers/16.jpg",
    soundcloudUrl: "https://soundcloud.com/jadsynth/sender",
    cover: {
      from: "#1f2a3a",
      to: "#05080f",
      accent: "#d4a574",
    },
  },
  {
    id: "17",
    title: "Genesis by J.A.D",
    album: "J.A.D",
    duration: "0:00",
    src: "/audio/genesis.mp3",
    artworkSrc: "/covers/17.jpg",
    soundcloudUrl: "https://soundcloud.com/jadsynth/genesis",
    cover: {
      from: "#1f2a3a",
      to: "#05080f",
      accent: "#d4a574",
    },
  },
  {
    id: "18",
    title: "Dream",
    album: "J.A.D",
    duration: "0:00",
    src: "/audio/dream.mp3",
    cover: {
      from: "#1f2a3a",
      to: "#05080f",
      accent: "#d4a574",
    },
  },
  {
    id: "19",
    title: "Jungle",
    album: "J.A.D",
    duration: "0:00",
    src: "/audio/Jungle.mp3",
    cover: {
      from: "#1f2a3a",
      to: "#05080f",
      accent: "#d4a574",
    },
  },
  {
    id: "20",
    title: "Lofi",
    album: "J.A.D",
    duration: "0:00",
    src: "/audio/Lofi.mp3",
    cover: {
      from: "#1f2a3a",
      to: "#05080f",
      accent: "#d4a574",
    },
  },
];
