#!/usr/bin/env node
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { createWriteStream } from "node:fs";
import { pipeline } from "node:stream/promises";
import { Readable } from "node:stream";
import { resolve, dirname, extname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const TRACKS_JSON = resolve(ROOT, "tracks.json");
const TRACKS_TS = resolve(ROOT, "src/lib/tracks.ts");
const COVERS_DIR = resolve(ROOT, "public/covers");

const OEMBED = "https://soundcloud.com/oembed?format=json&url=";

const DEFAULT_GRADIENT = { from: "#1f2a3a", to: "#05080f" };
const DEFAULT_ACCENT = "#d4a574";

function normalizeEntry(entry, index) {
  if (typeof entry === "string") {
    entry = { soundcloudUrl: entry };
  }
  return {
    id: entry.id || String(index + 1).padStart(2, "0"),
    soundcloudUrl: entry.soundcloudUrl,
    audioFile: entry.audioFile,
    title: entry.title,
    album: entry.album,
    duration: entry.duration || "0:00",
    mood: entry.mood,
    accent: entry.accent || DEFAULT_ACCENT,
    from: entry.from || DEFAULT_GRADIENT.from,
    to: entry.to || DEFAULT_GRADIENT.to,
  };
}

async function fetchOEmbed(url) {
  const res = await fetch(OEMBED + encodeURIComponent(url));
  if (!res.ok) throw new Error(`oEmbed ${res.status} for ${url}`);
  return res.json();
}

function upscaleArtwork(thumbnailUrl) {
  if (!thumbnailUrl) return null;
  return thumbnailUrl
    .replace(/-large\./, "-t1080x1080.")
    .replace(/-t500x500\./, "-t1080x1080.");
}

async function downloadImage(url, destPath) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Image ${res.status} for ${url}`);
  await pipeline(Readable.fromWeb(res.body), createWriteStream(destPath));
}

function escapeString(s) {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function tsFor(tracks) {
  const lines = [
    "// Generated by scripts/sync-tracks.mjs — do not edit by hand.",
    "// Source of truth: tracks.json",
    "",
    "export type Track = {",
    "  id: string;",
    "  title: string;",
    "  album: string;",
    "  duration: string;",
    "  src: string;",
    "  artworkSrc?: string;",
    "  soundcloudUrl?: string;",
    "  mood?: import('./moods').MoodName;",
    "  cover: {",
    "    from: string;",
    "    to: string;",
    "    accent: string;",
    "  };",
    "};",
    "",
    "export const tracks: Track[] = [",
  ];

  for (const t of tracks) {
    lines.push("  {");
    lines.push(`    id: "${escapeString(t.id)}",`);
    lines.push(`    title: "${escapeString(t.title)}",`);
    lines.push(`    album: "${escapeString(t.album)}",`);
    lines.push(`    duration: "${escapeString(t.duration)}",`);
    lines.push(`    src: "${escapeString(t.src)}",`);
    if (t.artworkSrc) {
      lines.push(`    artworkSrc: "${escapeString(t.artworkSrc)}",`);
    }
    if (t.soundcloudUrl) {
      lines.push(`    soundcloudUrl: "${escapeString(t.soundcloudUrl)}",`);
    }
    if (t.mood) {
      lines.push(`    mood: "${escapeString(t.mood)}",`);
    }
    lines.push("    cover: {");
    lines.push(`      from: "${escapeString(t.cover.from)}",`);
    lines.push(`      to: "${escapeString(t.cover.to)}",`);
    lines.push(`      accent: "${escapeString(t.cover.accent)}",`);
    lines.push("    },");
    lines.push("  },");
  }

  lines.push("];");
  lines.push("");
  return lines.join("\n");
}

async function main() {
  const raw = JSON.parse(await readFile(TRACKS_JSON, "utf8"));
  await mkdir(COVERS_DIR, { recursive: true });

  const out = [];
  const entries = raw.tracks.map(normalizeEntry);
  for (const entry of entries) {
    if (!entry.audioFile) {
      console.warn(`skip ${entry.id}: no audioFile`);
      continue;
    }

    if (!entry.soundcloudUrl) {
      if (!entry.title) {
        console.warn(
          `skip ${entry.id}: no soundcloudUrl and no explicit title`,
        );
        continue;
      }
      console.log(`local ${entry.id} … ✓ ${entry.title}`);
      out.push({
        id: entry.id,
        title: entry.title,
        album: entry.album || "—",
        duration: entry.duration,
        src: entry.audioFile,
        artworkSrc: undefined,
        soundcloudUrl: undefined,
        mood: entry.mood,
        cover: {
          from: entry.from,
          to: entry.to,
          accent: entry.accent,
        },
      });
      continue;
    }

    process.stdout.write(`fetching ${entry.id} … `);
    let meta;
    try {
      meta = await fetchOEmbed(entry.soundcloudUrl);
    } catch (err) {
      console.warn(`failed (${err.message})`);
      continue;
    }

    const upscaled = upscaleArtwork(meta.thumbnail_url);
    let artworkSrc;
    if (upscaled) {
      try {
        const ext = extname(new URL(upscaled).pathname) || ".jpg";
        const filename = `${entry.id}${ext}`;
        await downloadImage(upscaled, resolve(COVERS_DIR, filename));
        artworkSrc = `/covers/${filename}`;
      } catch (err) {
        console.warn(`(art ${err.message})`);
      }
    }

    out.push({
      id: entry.id,
      title: entry.title || meta.title || "Untitled",
      album: entry.album || meta.author_name || "—",
      duration: entry.duration,
      src: entry.audioFile,
      artworkSrc,
      soundcloudUrl: entry.soundcloudUrl,
      mood: entry.mood,
      cover: {
        from: entry.from,
        to: entry.to,
        accent: entry.accent,
      },
    });

    console.log(`✓ ${meta.title}`);
  }

  if (out.length === 0) {
    console.error(
      "\nrefusing to overwrite src/lib/tracks.ts with an empty list — fix the URLs in tracks.json and try again",
    );
    process.exit(1);
  }

  await writeFile(TRACKS_TS, tsFor(out), "utf8");
  console.log(`\nwrote ${out.length} tracks → src/lib/tracks.ts`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
